### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [mgmoldova/grid-project#1]
1)
здесь нет серого цвета.
![image](https://user-images.githubusercontent.com/8464662/88889777-4c228e00-d249-11ea-805f-614a83afa618.png)

2)
посмотрите в макете или шаблоне, но здесь должен быть какой-то отступ.
![image](https://user-images.githubusercontent.com/8464662/88889921-82600d80-d249-11ea-953c-91a9c0dbac2c.png)

**Comment by mgmoldova** [comment]
Исправлено.

**Comment by Alecto** [comment]
две ссылочки пожалуйста.

пт, 31 лип. 2020 о 15:31 mgmoldova <notifications@github.com> пише:

**Comment by mgmoldova** [comment]
GitPage:https://mgmoldova.github.io/grid-project/
GitHub: https://github.com/mgmoldova/grid-project/

**Comment by Alecto** [comment]
все отлично, работа принята.
только напишите имя фамилию, чтобы можно было отметить в журнале.

сб, 1 серп. 2020 о 13:15 mgmoldova <notifications@github.com> пише:

**Comment by mgmoldova** [comment]
Вы, вроде, уже отметили меня в журнале. Я просто исправил 2 минорные ошибки.
SkillUp FrontEnd. Платон Вадим, пн/ср 17-00

GitPage:https://mgmoldova.github.io/grid-project/
GitHub: https://github.com/mgmoldova/grid-project/

**Comment by Alecto** [comment]
проверил, работа в журнал  проставлено.

ср, 5 серп. 2020 о 12:10 mgmoldova <notifications@github.com> пише:
